spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: vegxer5@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  artemis:
    topic: mail-requests
    broker-url: tcp://localhost:61616
    user: admin
    password: admin