spring:
  artemis:
    mode: native
    host: localhost
    port: 5672
    user: admin
    password: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: vegxer5@gmail.com
    password: password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
app:
  artemis:
    topic: mail-requests