version: '3.5'
services:
  mailing:
    image: vscode.maxeem.ru/shop-sample-mailing:${MAILING_VERSION}
    container_name: shop-sample-mailing
    networks:
      - mailing-lan
    restart: always
    env_file: .env
    environment:
      TZ: "Europe/Moscow"
networks:
  mailing-lan:
    name: shop-sample-lan
    external: true
    driver: bridge